//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_VIDEOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class alquileres
    {
        public int id_alquiler { get; set; }
        public Nullable<long> ci_cliente { get; set; }
        public Nullable<int> id_juego { get; set; }
        public Nullable<System.DateTime> fecha_alquier { get; set; }
        public Nullable<int> id_tipo_juego { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual juegos juegos { get; set; }
        public virtual tipo_juego tipo_juego { get; set; }
    }
}
